services:
  db_memos:
    container_name: memos_db
    image: postgres:15
    environment:
      POSTGRES_DB: memos
      POSTGRES_USER: memos
      POSTGRES_PASSWORD: your-password
    volumes:
      - ./memos/data:/var/lib/postgresql/data
    networks:
      - memos_internal

  memos:
    container_name: memos
    image: neosmemo/memos:stable
    depends_on:
      - db_memos
    environment:
      - MEMOS_MODE=prod
      - MEMOS_DRIVER=postgres
      - MEMOS_DSN=postgresql://memos:your-password@db_memos:5432/memos?sslmode=disable
    labels:
       traefik.enable: true
       traefik.http.routers.memos.rule: Host(`memos.domain.here`)
       traefik.http.routers.memos.entrypoints: websecure
       traefik.http.routers.memos.tls.certresolver: myresolver
       traefik.http.services.memos.loadbalancer.server.port: 5230
       traefik.http.routers.memos.tls: true
       traefik.http.routers.memos.middlewares: security@docker, anubis@docker # Use to apply security middlewares
    networks:
      - entry
      - memos_internal
networks:
  memos_internal:
    internal: true